version: "3.9"
services:
  frontend:
    image: nginxinc/nginx-unprivileged
    volumes:
      - ./dist/apps/farmstand:/usr/share/nginx/html
    ports:
      - 4200:4200
  api:
    image: rosybone/api
    volumes:
      - ./dist/apps/api:/home/node/
    ports:
      - 3333:3333      
  mongodb:
    image: mongo
volumes:
  package:
